# T&T Lab 15 - 12th March
## Manish Ranjan Behera(1828249)

In [1]:
import numpy as np

### 1)WAP to find degree of a poynomial equation

In [7]:
n=int(input("Enter number of roots of the Polynomial Equation:"))
roots=[int(input(">>")) for x in range(0,n)]
p=np.poly1d(roots,True)
print("Polynomial Equation:\n",p)
print("\nDegree of the Polynomial Equation:",p.o)

Enter number of roots of the Polynomial Equation:5
>>8
>>3
>>7
>>2
>>7
Polynomial Equation:
    5      4       3        2
1 x - 27 x + 277 x - 1329 x + 2926 x - 2352

Degree of the Polynomial Equation: 5


### 2)WAP to find roots of a Quadratic Equation

In [11]:
print("Enter Coefficient of Quadratic Equations in decreasing order of exponent:")
coeff=[int(input(">>")) for x in range(0,3)]
p=np.poly1d(coeff,False)
print("Quadratic Equation:\n",p)
print("\nRoots of the Quadratic Equation:",p.r)

Enter Coefficient of Quadratic Equations in decreasing order of exponent:
>>2
>>5
>>-3
Quadratic Equation:
    2
2 x + 5 x - 3

Roots of the Quadratic Equation: [-3.   0.5]


### 3)WAP to print diagonal elements of a matrix

In [14]:
mat = np.matrix('[1, 2, 3; 4, 5, 6; 7, 8, 9]') 
print("Matrix:\n",mat)
diag = mat.diagonal() 
   
print("Diagonal of the Matrix:",diag)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Diagonal of the Matrix: [[1 5 9]]


### 4)WAP to find factorial of a number

In [13]:
num=int(input("Enter a Number:"))
fac=np.math.factorial(num)
print(f'{num}! = {fac}')

Enter a Number:12
12! = 479001600


### 5)WAP to find profit or loss for a given CP and SP

In [24]:
costPrice = float(input("Enter the Actual Cost of the Product: Rs."))
sellingPrice = float(input("Enter the Selling Price: Rs."))
 
if(costPrice > sellingPrice):
    p = costPrice - sellingPrice
    print("Total Loss Amount = Rs.{0}".format(p))
elif(sellingPrice > costPrice):
    p = sellingPrice - costPrice
    print("Total Profit = Rs.{0}".format(p))
else:
    print("No Profit No Loss!!!")

Enter the Actual Cost of the Product: Rs.78
Enter the Selling Price: Rs.113
Total Profit = Rs.35.0


### 6)WAP to sort the matrix row wise and Column wise

In [26]:
mat = np.array([[1,4], [3,1]])
print("Matrix:\n",a)


mat.sort(axis=1)
print("\nRow Wise Sort:\n",mat)

mat.sort(axis=0)
print("\nColumn Wise Sort:\n",mat)

Matrix:
 [[1 4]
 [3 1]]

Row Wise Sort:
 [[1 4]
 [1 3]]

Column Wise Sort:
 [[1 3]
 [1 4]]
