# T&T Lab 14 - 10th March
## Manish Ranjan Behera(1828249)

In [1]:
class classabc:
    def __init__(self,num):
        self.num=num
        
ob1=classabc(1)

In [2]:
#1D array
import numpy as np
a=np.array([1,2,3,'b'])
print(a)

['1' '2' '3' 'b']


In [3]:
#2D array
import numpy as np
b=np.array([[1,2],[3,4],[5,6]])
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
#minimum dimension
import numpy as np
b=np.array([1,2,3,4,5], ndmin=2)
print(b)

[[1 2 3 4 5]]


In [5]:
#parse parameter
import numpy as np
b=np.array([1,2,3,4,5], dtype=complex)
print(b)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


numpy.dtype(object, align, copy)

object : 

align : 

copy : Make new copy of data object

In [6]:
#Slicing
a=[1,2,3,4,5,6,7,8,9,10,11,12]
s=slice(2,7,2)
print(a[s])
print(a[2:7:2])

[3, 5, 7]
[3, 5, 7]


In [7]:
#Write a program to Slice a single value from a certain array
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
print(a[2:3])

[3]


In [8]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,0,1],[0,1,0]]
print(y)

[1 2 3]


### Create array of dimension 5x3 and perform integer indexing

In [9]:
#Illustrate integer indexing in an array of 5X3 
x = np.array([[1, 2,3], [4,5,6], [6,7,8],[9,10,11],[12,13,14]])
y= x[[1,2,1,0],[1,2,0,0]]
print(y)

[5 8 4 1]


## Iteration
` numpy.nditer`

In [10]:
a=np.arange(0,60,5)
a= a.reshape(3,4)

print(a)

print('Modified array is: ')
for x in np.nditer(a):
    print(x),

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Modified array is: 
0
5
10
15
20
25
30
35
40
45
50
55


In [11]:
import numpy as np
a = np.arange(0,80,5)
a = a.reshape(4,4)
print ('Original array is:')
print (a)
print ('\n')

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]
 [60 65 70 75]]




In [12]:
print ('Transpose of the original array is:')
b = a.T
print (b)
print('\n') 

Transpose of the original array is:
[[ 0 20 40 60]
 [ 5 25 45 65]
 [10 30 50 70]
 [15 35 55 75]]




In [13]:
print ('Sorted in C order:')
c = b.copy(order = 'C')
print (c)
for x in np.nditer(c):
    print (x)
print ('\n')

Sorted in C order:
[[ 0 20 40 60]
 [ 5 25 45 65]
 [10 30 50 70]
 [15 35 55 75]]
0
20
40
60
5
25
45
65
10
30
50
70
15
35
55
75




In [14]:
print ('Sorted in F-order:')
c = b.copy(order = 'F')
print (c)
for x in np.nditer(c):
    print(x)

Sorted in F-order:
[[ 0 20 40 60]
 [ 5 25 45 65]
 [10 30 50 70]
 [15 35 55 75]]
0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75


### WAP to find the sine, cosine and tangent values of the angles

In [15]:
import numpy as np
a = np.array([0,30,45,60,90])

print('Sine values of the angles:')
print(np.sin(a*np.pi/180))
print('\n')

print('Cosine values of the angles:')
print(np.cos(a*np.pi/180))
print('\n')

print('Tangent values of the angles:')
print(np.tan(a*np.pi/180))

Sine values of the angles:
[0.         0.5        0.70710678 0.8660254  1.        ]


Cosine values of the angles:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


Tangent values of the angles:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


### Q1. WAP TO FIND ROUND OFF VALUES OF DECIMAL POINTS

In [16]:
a=np.array([1.34,2.45,2.222,7,45])
print(a,1)
np.around(a)

[ 1.34   2.45   2.222  7.    45.   ] 1


array([ 1.,  2.,  2.,  7., 45.])

### Q2. WAP  TO DEMOSNTRATE BASIC ARITHMATIC OPERATIONS ON ARRAY

In [17]:
a=np.arange(0,10,2)
print(a)

print("\nAddition:\n")
b=a+2
print(b)

print("\nSubstraction:\n")
c=a-2
print(c)

print("\nMultiplication:\n")
d=a*2
print(d)

print("\nDivision:\n")
d=a/2
print(d)


[0 2 4 6 8]

Addition:

[ 2  4  6  8 10]

Substraction:

[-2  0  2  4  6]

Multiplication:

[ 0  4  8 12 16]

Division:

[0. 1. 2. 3. 4.]


### Q3. TAKE AN ARRAY WITH ATLEAT 7 INTEGER VALUES AND CALCULATE THEIR RECIPROCAL

In [18]:
a=np.arange(1,10)
print(a)

b=1/a
print(b)

[1 2 3 4 5 6 7 8 9]
[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111]


### Q4. FIND THE Nth POWER OF VALUES OF AN ARRAY

In [19]:
a=np.arange(0,5)
print(a)
u_in=int(input("Input the power: "))
b=pow(a,u_in)
print(b)

[0 1 2 3 4]
INput the power: 5
[   0    1   32  243 1024]


### Q5. WAP TO FIND THE PERCENTILE OF ARRAY ELEMENTS

In [20]:
a=np.arange(0,5)
print(np.percentile(a,50))

2.0


### Q6. WAP TO FIND THE MEDIAN OF ARRAY ELEMENT

In [21]:
a=np.arange(0,5)
print(np.median(a))

2.0


### Q7. WAP TO FIND THE AVERAGE, MODE, STANDARD DEVIATION , VARIANCE OF ARRAY ELEMENT

In [22]:
from scipy import stats

a=np.arange(1,10)
print(np.mean(a))
print(np.std(a))
print(np.var(a))

b=[1,2,3,3,3,3,3]
print(stats.mode(b)[0][0])

5.0
2.581988897471611
6.666666666666667
3


### Q8. IMPLEMENT ANY ONE SORT USING NUMPY

In [23]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr)) 


[0 1 2 3]
